### ISSUE TITLE
Error on line 45

### ISSUE THREAD

**Issue by wt9bind** [markcs/HDHR_epg#1]
Hi, firstly, thank you so much for making such a script where Plex really dropped the ball for us aussies.

I am running Cent OS 7 and ran the script without parsing it to a file and it appeared to have run, started returning XML data and then hung. I then parsed it to a file with:

./hr_epg.pl > HDHRPerth.XML and it returned:

Use of uninitialized value in concatenation (.) or string at ./hr_epg.pl line 45.

Line 45 is: printf "\t\t<icon src=\"".$items->{ImageURL}."\" />\n";

Thanks.

**Comment by markcs** [comment]
okay. 
Changes coming and we can debug after the update is uploaded

**Comment by markcs** [comment]
Please try again, but use `./hr_epg.pl  --output=HDHRPerth.xml --verbose` and let me know if you see the error

**Comment by misullivan** [comment]
I suspect the issue is caused by the discovery using the API not finding the box..  this could be for one of 2 reasons.

Either you’re using a different IP to the one the box uses to talk to the API which the latest version has “—ip <IP Address>” and specifying it an the IP of the box will fix that.

If the box has no internet access at all (and therefore can’t talk to the API) nothing is going to work to pull the guide out of it.

—verbose as a command line option will help diagnose both issues.

**Comment by wt9bind** [comment]
Hi, Thank you for your reply. 
Running it with: ./hr_epg.pl --output=HDHRPerth.xml instead of ./hr_epg.pl  > HDHRPerth.xml has resolved the issue.
Thanks

**Comment by markcs** [comment]
@wt9bind No need to use the ">" anymore.  

Just run ./hr_epg.pl --output=HDHRPerth.xml instead.
